### ISSUE TITLE
Acmeproxy not register any domain

### ISSUE THREAD

**Issue by nicrf** [lukacu/docker-frps#5]
Hi,

I tried to use this docker, with these param : 
```
version: '2'
services:
  filebrowser:
    image: lukacu/frps
    container_name: frps
    restart: unless-stopped
    network_mode: "host"
    environment:
      - FRPS_DASHBOARD=true
      - FRPS_DASHBOARD_USER=admin
      - FRPS_DASHBOARD_PASSWORD=password
      - FRPS_AUTH_TOKEN=password
      - FRPS_SUBDOMAIN_HOST=domain.com
      - FRPS_PERSISTENT_PORTS=true
      - FRPS_LETSENCRYPT_EMAIL="email@domain.com"
      - FRPS_TCP_MUX=true
```

And evry thing seems to work, i got my tunnel connect and work on http : 
![image](https://user-images.githubusercontent.com/29955546/115063396-82786a00-9eb9-11eb-9e97-a00661f97ffc.png)
![image](https://user-images.githubusercontent.com/29955546/115064038-6d500b00-9eba-11eb-914b-4566411f39f3.png)

I.e. fpsc ini : 
```
# frpc.ini
[common]
server_addr = domain.com
server_port = 7000
token =password
pool_count = 5
tcp_mux = true
login_fail_exit = false
tls_enable = true
admin_addr = domain.com
admin_port =7400
admin_user = admin
admin_pwd = =password

[frp_intranet_1]
type = http # and tried https to
use_encryption = true
use_compression = true
local_ip = 127.0.0.1
local_port = 8081
subdomain = intranet
remote_port = 0
host_header_rewrite=true
```

But, i cannot get Acmeproxy working, the log of Acmeproxy say only it have open the port 444. I see on host my port 444 is used by acme.

I tried stop stop all service in the docker and start one by one (acme, frps)  : 
```
/usr/local/bin/acmeproxy --api 9002 --domain domain.com &
/usr/local/bin/frps -c /etc/frps.ini 2>&1
```
Same result, no https proxy. I tried to check go code, but I do not see what does not work. I check the /data volume and there is no file except ports.map.

Can you help me with that?

Log : 
![image](https://user-images.githubusercontent.com/29955546/115065257-e9971e00-9ebb-11eb-9802-1929d35b3c7f.png)
